name: Run Tests # Name of your workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest # Specifies the operating system runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the version of Node.js

      - name: Install Dependencies
        run: npm install # Command to install project dependencies

      - name: Install playwright
        run: npx playwright install

      - name: Run Tests
        run: npm run test:headless # Command to execute your tests (often defined in your package.json)

      - name: Upload failure screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: vitest-failure-screenshots
          pat: .vitest-attachments
