name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Tests
        id: run_tests
        run: npm run test:headless
        continue-on-error: true

      - name: Debug Files
        run: |
          pwd
          ls -la

      - uses: actions/upload-artifact@v4
        with:
          name: Upload Screenshots
          path: .vitest-attachments/**
          if-no-files-found: ignore
          retention-days: 1

      # - name: Upload failure screenshots
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: vitest-failure-screenshots
      #     path: .vitest-attachments
      #     if-no-files-found: ignore

      # - name: Fail job if tests failed
      #   if: steps.run_tests.outcome == 'failure'
      #   run: exit 1
